(() => {
  'use strict';
  // Curated offline starter index. Search always offers an explicit manual-name
  // fallback, so a missing institution never blocks signup.
  const rows = [
    ['s-dhaka-collegiate','school','Dhaka Collegiate School','Dhaka','ঢাকা কলেজিয়েট স্কুল'],
    ['s-dhaka-residential','both','Dhaka Residential Model College','Dhaka','DRMC|ঢাকা রেসিডেনসিয়াল মডেল কলেজ'],
    ['s-viqarunnisa','both','Viqarunnisa Noon School and College','Dhaka','VNSC|ভিকারুননিসা নূন স্কুল অ্যান্ড কলেজ'],
    ['s-ideal','both','Ideal School and College','Dhaka','আইডিয়াল স্কুল অ্যান্ড কলেজ|Motijheel Ideal'],
    ['s-motijheel-govt-boys','school','Motijheel Government Boys High School','Dhaka','মতিঝিল সরকারি বালক উচ্চ বিদ্যালয়'],
    ['s-motijheel-govt-girls','school','Motijheel Government Girls High School','Dhaka','মতিঝিল সরকারি বালিকা উচ্চ বিদ্যালয়'],
    ['s-government-laboratory','school','Government Laboratory High School','Dhaka','গভর্নমেন্ট ল্যাবরেটরি হাই স্কুল'],
    ['s-dhanmondi-govt-boys','school','Dhanmondi Government Boys High School','Dhaka','ধানমন্ডি সরকারি বালক উচ্চ বিদ্যালয়'],
    ['s-bangladesh-international','both','Bangladesh International School and College','Dhaka','BISC|বাংলাদেশ ইন্টারন্যাশনাল স্কুল অ্যান্ড কলেজ'],
    ['s-st-joseph','both','St. Joseph Higher Secondary School','Dhaka','সেন্ট যোসেফ উচ্চ মাধ্যমিক বিদ্যালয়'],
    ['s-holy-cross','higher','Holy Cross College','Dhaka','হলি ক্রস কলেজ'],
    ['s-notre-dame','higher','Notre Dame College, Dhaka','Dhaka','NDC|নটর ডেম কলেজ'],
    ['s-rajuk','both','RAJUK Uttara Model College','Dhaka','RUMC|রাজউক উত্তরা মডেল কলেজ'],
    ['s-adamjee-cantonment','both','Adamjee Cantonment College','Dhaka','ACC|আদমজী ক্যান্টনমেন্ট কলেজ'],
    ['s-baf-shaheen-dhaka','both','BAF Shaheen College Dhaka','Dhaka','বিএএফ শাহীন কলেজ ঢাকা'],
    ['s-milestone','both','Milestone College','Dhaka','মাইলস্টোন কলেজ'],
    ['s-mirpur-cantonment','both','Mirpur Cantonment Public School and College','Dhaka','MCPSC|মিরপুর ক্যান্টনমেন্ট পাবলিক স্কুল অ্যান্ড কলেজ'],
    ['s-manikganj-govt','school','Manikganj Government High School','Manikganj','মানিকগঞ্জ সরকারি উচ্চ বিদ্যালয়'],
    ['s-narayanganj-high','school','Narayanganj High School and College','Narayanganj','নারায়ণগঞ্জ হাই স্কুল অ্যান্ড কলেজ'],
    ['s-arihazar-pilot','school','Araihazar Government Pilot Model High School','Narayanganj','আড়াইহাজার সরকারি পাইলট মডেল উচ্চ বিদ্যালয়'],
    ['s-gazipur-cantonment','both','Gazipur Cantonment Public School and College','Gazipur','গাজীপুর ক্যান্টনমেন্ট পাবলিক স্কুল অ্যান্ড কলেজ'],
    ['s-rani-bilasmoni','school','Rani Bilasmoni Government Boys High School','Gazipur','রানী বিলাসমণি সরকারি বালক উচ্চ বিদ্যালয়'],
    ['s-bindubasini-boys','school','Bindubasini Government Boys High School','Tangail','বিন্দুবাসিনী সরকারি বালক উচ্চ বিদ্যালয়'],
    ['s-bindubasini-girls','school','Bindubasini Government Girls High School','Tangail','বিন্দুবাসিনী সরকারি বালিকা উচ্চ বিদ্যালয়'],
    ['s-faridpur-zilla','school','Faridpur Zilla School','Faridpur','ফরিদপুর জিলা স্কুল'],
    ['s-saroda-sundari','school','Saroda Sundari Girls High School','Faridpur','সারদা সুন্দরী বালিকা উচ্চ বিদ্যালয়'],
    ['s-chittagong-collegiate','school','Chittagong Collegiate School','Chattogram','চট্টগ্রাম কলেজিয়েট স্কুল'],
    ['s-chittagong-govt-high','school','Chittagong Government High School','Chattogram','চট্টগ্রাম সরকারি উচ্চ বিদ্যালয়'],
    ['s-dr-khastagir','school','Dr. Khastagir Government Girls High School','Chattogram','ডা. খাস্তগীর সরকারি বালিকা উচ্চ বিদ্যালয়'],
    ['s-nasirabad-boys','school','Nasirabad Government High School','Chattogram','নাসিরাবাদ সরকারি উচ্চ বিদ্যালয়'],
    ['s-cmp-school','both','Chattogram Metropolitan Police School and College','Chattogram','CMP School and College|সিএমপি স্কুল অ্যান্ড কলেজ'],
    ['s-baf-shaheen-chattogram','both','BAF Shaheen College Chattogram','Chattogram','বিএএফ শাহীন কলেজ চট্টগ্রাম'],
    ['s-cantonment-english-chattogram','both','Chittagong Cantonment Public College','Chattogram','CCPC|চট্টগ্রাম ক্যান্টনমেন্ট পাবলিক কলেজ'],
    ['s-cox-govt-high','school','Cox’s Bazar Government High School','Cox’s Bazar','কক্সবাজার সরকারি উচ্চ বিদ্যালয়|Cox Bazar Govt High'],
    ['s-cox-govt-girls','school','Cox’s Bazar Government Girls High School','Cox’s Bazar','কক্সবাজার সরকারি বালিকা উচ্চ বিদ্যালয়'],
    ['s-cox-cantonment','both','Cox’s Bazar International School','Cox’s Bazar','কক্সবাজার ইন্টারন্যাশনাল স্কুল'],
    ['s-comilla-zilla','school','Cumilla Zilla School','Cumilla','কুমিল্লা জিলা স্কুল|Comilla Zilla School'],
    ['s-nawab-faizunnesa','school','Nawab Faizunnesa Government Girls High School','Cumilla','নওয়াব ফয়জুন্নেছা সরকারি বালিকা উচ্চ বিদ্যালয়'],
    ['s-comilla-cadet','school','Cumilla Cadet College','Cumilla','কুমিল্লা ক্যাডেট কলেজ|Comilla Cadet College'],
    ['s-feni-govt-pilot','school','Feni Government Pilot High School','Feni','ফেনী সরকারি পাইলট উচ্চ বিদ্যালয়'],
    ['s-noakhali-zilla','school','Noakhali Zilla School','Noakhali','নোয়াখালী জিলা স্কুল'],
    ['s-lakshmipur-adarsha','school','Lakshmipur Adarsha Samad Government High School','Lakshmipur','লক্ষ্মীপুর আদর্শ সামাদ সরকারি উচ্চ বিদ্যালয়'],
    ['s-rangamati-govt','school','Rangamati Government High School','Rangamati','রাঙামাটি সরকারি উচ্চ বিদ্যালয়'],
    ['s-khagrachari-govt','school','Khagrachhari Government High School','Khagrachhari','খাগড়াছড়ি সরকারি উচ্চ বিদ্যালয়'],
    ['s-bandarban-cantonment','both','Bandarban Cantonment Public School and College','Bandarban','বান্দরবান ক্যান্টনমেন্ট পাবলিক স্কুল অ্যান্ড কলেজ'],
    ['s-rajshahi-collegiate','school','Rajshahi Collegiate School','Rajshahi','রাজশাহী কলেজিয়েট স্কুল'],
    ['s-pn-girls','school','P. N. Government Girls High School','Rajshahi','পিএন সরকারি বালিকা উচ্চ বিদ্যালয়'],
    ['s-rajshahi-cadet','school','Rajshahi Cadet College','Rajshahi','রাজশাহী ক্যাডেট কলেজ'],
    ['s-bogra-zilla','school','Bogra Zilla School','Bogura','বগুড়া জিলা স্কুল'],
    ['s-bogra-govt-girls','school','Bogra Government Girls High School','Bogura','বগুড়া সরকারি বালিকা উচ্চ বিদ্যালয়'],
    ['s-pabna-zilla','school','Pabna Zilla School','Pabna','পাবনা জিলা স্কুল'],
    ['s-sirajganj-bl','school','B. L. Government High School','Sirajganj','বি এল সরকারি উচ্চ বিদ্যালয়'],
    ['s-naogaon-zilla','school','Naogaon K. D. Government High School','Naogaon','নওগাঁ কে ডি সরকারি উচ্চ বিদ্যালয়'],
    ['s-natore-govt-boys','school','Natore Government Boys High School','Natore','নাটোর সরকারি বালক উচ্চ বিদ্যালয়'],
    ['s-chapainawabganj-harimohan','school','Harimohan Government High School','Chapainawabganj','হরিমোহন সরকারি উচ্চ বিদ্যালয়'],
    ['s-khulna-zilla','school','Khulna Zilla School','Khulna','খুলনা জিলা স্কুল'],
    ['s-coronation-girls','school','Government Coronation Secondary Girls School','Khulna','করোনেশন সরকারি মাধ্যমিক বালিকা বিদ্যালয়'],
    ['s-jashore-zilla','school','Jashore Zilla School','Jashore','যশোর জিলা স্কুল|Jessore Zilla School'],
    ['s-jhenaidah-cadet','school','Jhenaidah Cadet College','Jhenaidah','ঝিনাইদহ ক্যাডেট কলেজ'],
    ['s-kushtia-zilla','school','Kushtia Zilla School','Kushtia','কুষ্টিয়া জিলা স্কুল'],
    ['s-satkhira-govt','school','Satkhira Government High School','Satkhira','সাতক্ষীরা সরকারি উচ্চ বিদ্যালয়'],
    ['s-barisal-zilla','school','Barishal Zilla School','Barishal','বরিশাল জিলা স্কুল|Barisal Zilla School'],
    ['s-barisal-govt-girls','school','Barishal Government Girls High School','Barishal','বরিশাল সরকারি বালিকা উচ্চ বিদ্যালয়'],
    ['s-barisal-cadet','school','Barishal Cadet College','Barishal','বরিশাল ক্যাডেট কলেজ'],
    ['s-patuakhali-jubilee','school','Patuakhali Government Jubilee High School','Patuakhali','পটুয়াখালী সরকারি জুবিলী উচ্চ বিদ্যালয়'],
    ['s-bhola-govt-high','school','Bhola Government High School','Bhola','ভোলা সরকারি উচ্চ বিদ্যালয়'],
    ['s-sylhet-pilot','school','Sylhet Government Pilot High School','Sylhet','সিলেট সরকারি পাইলট উচ্চ বিদ্যালয়'],
    ['s-blue-bird','both','Blue Bird High School and College','Sylhet','ব্লু বার্ড হাই স্কুল অ্যান্ড কলেজ'],
    ['s-sylhet-cadet','school','Sylhet Cadet College','Sylhet','সিলেট ক্যাডেট কলেজ'],
    ['s-moulvibazar-govt','school','Moulvibazar Government High School','Moulvibazar','মৌলভীবাজার সরকারি উচ্চ বিদ্যালয়'],
    ['s-habiganj-govt','school','Habiganj Government High School','Habiganj','হবিগঞ্জ সরকারি উচ্চ বিদ্যালয়'],
    ['s-sunamganj-jubilee','school','Government Jubilee High School, Sunamganj','Sunamganj','সরকারি জুবিলী উচ্চ বিদ্যালয় সুনামগঞ্জ'],
    ['s-mymensingh-zilla','school','Mymensingh Zilla School','Mymensingh','ময়মনসিংহ জিলা স্কুল'],
    ['s-vidyamoyee','school','Vidyamoyee Government Girls High School','Mymensingh','বিদ্যাময়ী সরকারি বালিকা উচ্চ বিদ্যালয়'],
    ['s-mymensingh-girls-cadet','school','Mymensingh Girls’ Cadet College','Mymensingh','ময়মনসিংহ গার্লস ক্যাডেট কলেজ'],
    ['s-jamalpur-zilla','school','Jamalpur Zilla School','Jamalpur','জামালপুর জিলা স্কুল'],
    ['s-netrokona-anjuman','school','Anjuman Adarsha Government High School','Netrokona','আঞ্জুমান আদর্শ সরকারি উচ্চ বিদ্যালয়'],
    ['s-rangpur-zilla','school','Rangpur Zilla School','Rangpur','রংপুর জিলা স্কুল'],
    ['s-rangpur-cadet','school','Rangpur Cadet College','Rangpur','রংপুর ক্যাডেট কলেজ'],
    ['s-dinajpur-zilla','school','Dinajpur Zilla School','Dinajpur','দিনাজপুর জিলা স্কুল'],
    ['s-thakurgaon-govt-boys','school','Thakurgaon Government Boys High School','Thakurgaon','ঠাকুরগাঁও সরকারি বালক উচ্চ বিদ্যালয়'],
    ['s-kurigram-govt','school','Kurigram Government High School','Kurigram','কুড়িগ্রাম সরকারি উচ্চ বিদ্যালয়'],

    ['h-du','higher','University of Dhaka','Dhaka','DU|ঢাকা বিশ্ববিদ্যালয়'],
    ['h-buet','higher','Bangladesh University of Engineering and Technology','Dhaka','BUET|বুয়েট'],
    ['h-bup','higher','Bangladesh University of Professionals','Dhaka','BUP|বাংলাদেশ ইউনিভার্সিটি অব প্রফেশনালস'],
    ['h-jnu','higher','Jagannath University','Dhaka','JnU|জগন্নাথ বিশ্ববিদ্যালয়'],
    ['h-sher-e-bangla','higher','Sher-e-Bangla Agricultural University','Dhaka','SAU|শেরেবাংলা কৃষি বিশ্ববিদ্যালয়'],
    ['h-butext','higher','Bangladesh University of Textiles','Dhaka','BUTEX|বাংলাদেশ টেক্সটাইল বিশ্ববিদ্যালয়'],
    ['h-du-seven-dhaka-college','higher','Dhaka College','Dhaka','ঢাকা কলেজ'],
    ['h-eden','higher','Eden Mohila College','Dhaka','ইডেন মহিলা কলেজ'],
    ['h-titumir','higher','Government Titumir College','Dhaka','সরকারি তিতুমীর কলেজ'],
    ['h-bangla-college','higher','Government Bangla College','Dhaka','সরকারি বাঙলা কলেজ'],
    ['h-kabi-nazrul','higher','Kabi Nazrul Government College','Dhaka','কবি নজরুল সরকারি কলেজ'],
    ['h-suhrwardy','higher','Government Shaheed Suhrawardy College','Dhaka','সরকারি শহীদ সোহরাওয়ার্দী কলেজ'],
    ['h-brac','higher','BRAC University','Dhaka','BRACU|ব্র্যাক বিশ্ববিদ্যালয়'],
    ['h-nsu','higher','North South University','Dhaka','NSU|নর্থ সাউথ বিশ্ববিদ্যালয়'],
    ['h-iub','higher','Independent University, Bangladesh','Dhaka','IUB|ইন্ডিপেনডেন্ট ইউনিভার্সিটি বাংলাদেশ'],
    ['h-aiub','higher','American International University-Bangladesh','Dhaka','AIUB|আমেরিকান ইন্টারন্যাশনাল ইউনিভার্সিটি বাংলাদেশ'],
    ['h-ewu','higher','East West University','Dhaka','EWU|ইস্ট ওয়েস্ট বিশ্ববিদ্যালয়'],
    ['h-uiu','higher','United International University','Dhaka','UIU|ইউনাইটেড ইন্টারন্যাশনাল ইউনিভার্সিটি'],
    ['h-aust','higher','Ahsanullah University of Science and Technology','Dhaka','AUST|আহসানউল্লাহ বিজ্ঞান ও প্রযুক্তি বিশ্ববিদ্যালয়'],
    ['h-daffodil','higher','Daffodil International University','Dhaka','DIU|ড্যাফোডিল ইন্টারন্যাশনাল ইউনিভার্সিটি'],
    ['h-iut','higher','Islamic University of Technology','Gazipur','IUT|ইসলামিক ইউনিভার্সিটি অব টেকনোলজি'],
    ['h-bou','higher','Bangladesh Open University','Gazipur','BOU|বাংলাদেশ উন্মুক্ত বিশ্ববিদ্যালয়'],
    ['h-duet','higher','Dhaka University of Engineering and Technology','Gazipur','DUET|ঢাকা প্রকৌশল ও প্রযুক্তি বিশ্ববিদ্যালয়'],
    ['h-bsmrau','higher','Gazipur Agricultural University','Gazipur','GAU|গাজীপুর কৃষি বিশ্ববিদ্যালয়'],
    ['h-jahangirnagar','higher','Jahangirnagar University','Savar','JU|জাহাঙ্গীরনগর বিশ্ববিদ্যালয়'],
    ['h-maw-bhashani','higher','Mawlana Bhashani Science and Technology University','Tangail','MBSTU|মাওলানা ভাসানী বিজ্ঞান ও প্রযুক্তি বিশ্ববিদ্যালয়'],
    ['h-bangabandhu-digital','higher','Bangabandhu Sheikh Mujibur Rahman Digital University','Gazipur','BDU|ডিজিটাল বিশ্ববিদ্যালয়'],
    ['h-buft','higher','BGMEA University of Fashion and Technology','Dhaka','BUFT|বিজিএমইএ ইউনিভার্সিটি অব ফ্যাশন অ্যান্ড টেকনোলজি'],

    ['h-cu','higher','University of Chittagong','Chattogram','CU|চট্টগ্রাম বিশ্ববিদ্যালয়'],
    ['h-cuet','higher','Chittagong University of Engineering and Technology','Chattogram','CUET|চুয়েট'],
    ['h-cvasu','higher','Chattogram Veterinary and Animal Sciences University','Chattogram','CVASU|চট্টগ্রাম ভেটেরিনারি ও এনিম্যাল সাইন্সেস বিশ্ববিদ্যালয়'],
    ['h-chittagong-college','higher','Chittagong College','Chattogram','চট্টগ্রাম কলেজ'],
    ['h-mohsin','higher','Government Hazi Muhammad Mohsin College','Chattogram','সরকারি হাজী মুহাম্মদ মহসিন কলেজ'],
    ['h-premier','higher','Premier University','Chattogram','PUC|প্রিমিয়ার বিশ্ববিদ্যালয়'],
    ['h-iuc','higher','International Islamic University Chittagong','Chattogram','IIUC|আন্তর্জাতিক ইসলামী বিশ্ববিদ্যালয় চট্টগ্রাম'],
    ['h-asian-women','higher','Asian University for Women','Chattogram','AUW|এশিয়ান ইউনিভার্সিটি ফর উইমেন'],
    ['h-cou','higher','Comilla University','Cumilla','CoU|কুমিল্লা বিশ্ববিদ্যালয়'],
    ['h-comilla-victoria','higher','Cumilla Victoria Government College','Cumilla','কুমিল্লা ভিক্টোরিয়া সরকারি কলেজ|Comilla Victoria College'],
    ['h-noakhali-science','higher','Noakhali Science and Technology University','Noakhali','NSTU|নোয়াখালী বিজ্ঞান ও প্রযুক্তি বিশ্ববিদ্যালয়'],
    ['h-feni-university','higher','Feni University','Feni','ফেনী বিশ্ববিদ্যালয়'],

    ['h-ru','higher','University of Rajshahi','Rajshahi','RU|রাজশাহী বিশ্ববিদ্যালয়'],
    ['h-ruet','higher','Rajshahi University of Engineering and Technology','Rajshahi','RUET|রুয়েট'],
    ['h-rajshahi-college','higher','Rajshahi College','Rajshahi','রাজশাহী কলেজ'],
    ['h-north-bengal','higher','North Bengal International University','Rajshahi','NBIU|নর্থ বেঙ্গল ইন্টারন্যাশনাল ইউনিভার্সিটি'],
    ['h-pust','higher','Pabna University of Science and Technology','Pabna','PUST|পাবনা বিজ্ঞান ও প্রযুক্তি বিশ্ববিদ্যালয়'],
    ['h-bauet','higher','Bangladesh Army University of Engineering and Technology','Natore','BAUET|বাংলাদেশ আর্মি ইউনিভার্সিটি অব ইঞ্জিনিয়ারিং অ্যান্ড টেকনোলজি'],
    ['h-rabindra','higher','Rabindra University, Bangladesh','Sirajganj','RUB|রবীন্দ্র বিশ্ববিদ্যালয় বাংলাদেশ'],

    ['h-ku','higher','Khulna University','Khulna','KU|খুলনা বিশ্ববিদ্যালয়'],
    ['h-kuet','higher','Khulna University of Engineering and Technology','Khulna','KUET|কুয়েট'],
    ['h-khulna-govt-womens','higher','Khulna Government Women’s College','Khulna','খুলনা সরকারি মহিলা কলেজ'],
    ['h-jashore-science','higher','Jashore University of Science and Technology','Jashore','JUST|যশোর বিজ্ঞান ও প্রযুক্তি বিশ্ববিদ্যালয়'],
    ['h-islamic-university','higher','Islamic University, Bangladesh','Kushtia','IU|ইসলামী বিশ্ববিদ্যালয় কুষ্টিয়া'],
    ['h-kushtia-govt','higher','Kushtia Government College','Kushtia','কুষ্টিয়া সরকারি কলেজ'],

    ['h-bu','higher','University of Barishal','Barishal','BU|বরিশাল বিশ্ববিদ্যালয়'],
    ['h-bm-college','higher','Government Brojomohun College','Barishal','BM College|সরকারি ব্রজমোহন কলেজ'],
    ['h-pstu','higher','Patuakhali Science and Technology University','Patuakhali','PSTU|পটুয়াখালী বিজ্ঞান ও প্রযুক্তি বিশ্ববিদ্যালয়'],
    ['h-sylhet-agri','higher','Sylhet Agricultural University','Sylhet','SAU|সিলেট কৃষি বিশ্ববিদ্যালয়'],
    ['h-sust','higher','Shahjalal University of Science and Technology','Sylhet','SUST|শাহজালাল বিজ্ঞান ও প্রযুক্তি বিশ্ববিদ্যালয়'],
    ['h-mc-college','higher','Murari Chand College','Sylhet','MC College|মুরারিচাঁদ কলেজ'],
    ['h-leading','higher','Leading University','Sylhet','লিডিং ইউনিভার্সিটি'],
    ['h-metropolitan','higher','Metropolitan University','Sylhet','মেট্রোপলিটন ইউনিভার্সিটি'],

    ['h-bau','higher','Bangladesh Agricultural University','Mymensingh','BAU|বাংলাদেশ কৃষি বিশ্ববিদ্যালয়'],
    ['h-jkkniu','higher','Jatiya Kabi Kazi Nazrul Islam University','Mymensingh','JKKNIU|জাতীয় কবি কাজী নজরুল ইসলাম বিশ্ববিদ্যালয়'],
    ['h-ananda-mohan','higher','Ananda Mohan College','Mymensingh','আনন্দ মোহন কলেজ'],
    ['h-sheikh-hasina','higher','Netrokona University','Netrokona','নেত্রকোনা বিশ্ববিদ্যালয়'],
    ['h-begum-rokeya','higher','Begum Rokeya University, Rangpur','Rangpur','BRUR|বেগম রোকেয়া বিশ্ববিদ্যালয়'],
    ['h-carmichael','higher','Carmichael College','Rangpur','কারমাইকেল কলেজ'],
    ['h-hstu','higher','Hajee Mohammad Danesh Science and Technology University','Dinajpur','HSTU|হাজী মোহাম্মদ দানেশ বিজ্ঞান ও প্রযুক্তি বিশ্ববিদ্যালয়'],
    ['h-bsmrstu','higher','Gopalganj Science and Technology University','Gopalganj','GSTU|গোপালগঞ্জ বিজ্ঞান ও প্রযুক্তি বিশ্ববিদ্যালয়'],
    ['h-bsmrmu','higher','Bangladesh Maritime University','Dhaka','BMU|বাংলাদেশ মেরিটাইম বিশ্ববিদ্যালয়'],
    ['h-nu','higher','National University, Bangladesh','Gazipur','NU|জাতীয় বিশ্ববিদ্যালয়'],
    ['h-medical-dmc','higher','Dhaka Medical College','Dhaka','DMC|ঢাকা মেডিকেল কলেজ'],
    ['h-medical-cmc','higher','Chittagong Medical College','Chattogram','CMC|চট্টগ্রাম মেডিকেল কলেজ'],
    ['h-medical-rmc','higher','Rajshahi Medical College','Rajshahi','RMC|রাজশাহী মেডিকেল কলেজ'],
    ['h-medical-mmc','higher','Mymensingh Medical College','Mymensingh','MMC|ময়মনসিংহ মেডিকেল কলেজ'],
    ['h-medical-somc','higher','Sylhet MAG Osmani Medical College','Sylhet','SOMC|সিলেট এম এ জি ওসমানী মেডিকেল কলেজ'],
    ['h-medical-sbmc','higher','Sher-e-Bangla Medical College','Barishal','SBMC|শের-ই-বাংলা মেডিকেল কলেজ']
  ];

  const institutions = rows.map(([id, type, name, district, aliases = '']) => Object.freeze({
    id, type, name, district, aliases: Object.freeze(aliases.split('|').filter(Boolean))
  }));
  Object.defineProperty(window, 'AdmissionHubInstitutionsV1', {
    value: Object.freeze(institutions), configurable: false, writable: false
  });
  Object.defineProperty(window, 'AdmissionHubInstitutionsMetaV1', {
    value: Object.freeze({
      country: 'BD',
      coverage: 'curated-starter-index',
      completeCoverageClaimed: false,
      fallback: Object.freeze({ mode: 'manual', alwaysAvailable: true })
    }),
    configurable: false,
    writable: false
  });
})();
