(() => {
  const PKEY='admission_phase345_v1';
  const loadP=()=>{try{return JSON.parse(localStorage.getItem(PKEY)||'{}')}catch{return {}}};
  const saveP=x=>localStorage.setItem(PKEY,JSON.stringify(x));
  const P=loadP(); P.savedWords=P.savedWords||[]; P.vocab=P.vocab||[]; P.weak=P.weak||[]; P.covered=P.covered||[]; P.examHistory=P.examHistory||[]; saveP(P);
  const pEsc=s=>{const d=document.createElement('div');d.textContent=String(s??'');return d.innerHTML};
  const pStore=(key,val)=>{P[key]=val;saveP(P)};
  const pBtn=(label,fn,cls='btn')=>`<button class="${cls}" onclick="${fn}">${label}</button>`;
  const gk=[
    ['বাংলাদেশের সংবিধানের কোন অনুচ্ছেদে রাষ্ট্রভাষা বাংলার কথা বলা হয়েছে?',['৩','২','৪','৭'],'৩','বাংলাদেশের সংবিধান, অনুচ্ছেদ ৩','https://bdlaws.minlaw.gov.bd/act-367.html'],
    ['জাতিসংঘের সদর দপ্তর কোথায় অবস্থিত?',['নিউইয়র্ক','জেনেভা','প্যারিস','লন্ডন'],'নিউইয়র্ক','United Nations Headquarters','https://www.un.org/en/about-us/un-headquarters'],
    ['SDG-এর মোট লক্ষ্য সংখ্যা কত?',['১৭','১৫','১৬','২০'],'১৭','জাতিসংঘের Sustainable Development Goals','https://sdgs.un.org/goals'],
    ['বাংলাদেশের জাতীয় সংসদ ভবনের স্থপতি কে?',['লুই আই কান','এফ আর খান','মুজহারুল ইসলাম','ল্য করবুজিয়ে'],'লুই আই কান','Banglapedia: National Parliament House','https://en.banglapedia.org/index.php/National_Parliament_House'],
    ['পদ্মা সেতু কোন নদীর ওপর নির্মিত?',['পদ্মা','যমুনা','মেঘনা','কর্ণফুলী'],'পদ্মা','বাংলাদেশ সেতু কর্তৃপক্ষ','https://bba.gov.bd/'],
    ['বিশ্বের বৃহত্তম ম্যানগ্রোভ বন কোনটি?',['সুন্দরবন','আমাজন','কঙ্গো','বোরনিও'],'সুন্দরবন','UNESCO World Heritage Centre','https://whc.unesco.org/en/list/798/'],
    ['বাংলাদেশের স্বাধীনতা দিবস কবে?',['২৬ মার্চ','১৬ ডিসেম্বর','২১ ফেব্রুয়ারি','১৭ এপ্রিল'],'২৬ মার্চ','বাংলাদেশ সরকারের জাতীয় পোর্টাল','https://bangladesh.gov.bd/'],
    ['আন্তর্জাতিক মাতৃভাষা দিবস কবে পালিত হয়?',['২১ ফেব্রুয়ারি','২৬ মার্চ','১৬ ডিসেম্বর','৫ জুন'],'২১ ফেব্রুয়ারি','UNESCO','https://www.unesco.org/en/days/international-mother-language'],
    ['SAARC-এর সদর দপ্তর কোথায়?',['কাঠমান্ডু','ঢাকা','নয়াদিল্লি','কলম্বো'],'কাঠমান্ডু','SAARC Secretariat','https://saarc-sec.org/'],
    ['বাংলাদেশের কেন্দ্রীয় ব্যাংকের নাম কী?',['বাংলাদেশ ব্যাংক','সোনালী ব্যাংক','ঢাকা ব্যাংক','জনতা ব্যাংক'],'বাংলাদেশ ব্যাংক','Bangladesh Bank','https://www.bb.org.bd/']
  ];
  const engCats=['Vocabulary','Correct Spelling','One Word Substitution','Idioms & Phrases','Phrasal Verbs','Appropriate Preposition','Analogy','Commonly Confused Words','Important Word Pairs','Foreign Words','Abbreviations & Terms','Literary Facts'];
  const benCats=['সাহিত্যিক ও লেখক','গ্রন্থ ও গ্রন্থকার','কবিতা ও কাব্যগ্রন্থ','উপন্যাস ও উপন্যাসিক','গল্প ও গল্পকার','নাটক ও নাট্যকার','প্রবন্ধ ও প্রাবন্ধিক','চরিত্র ও সংশ্লিষ্ট গ্রন্থ','ছদ্মনাম/উপাধি','জন্ম-মৃত্যু ও গুরুত্বপূর্ণ সাল','সাহিত্যিক যুগ ও আন্দোলন','ভাষা আন্দোলন/মুক্তিযুদ্ধের সাহিত্য','বাগধারা','প্রবাদ-প্রবচন','সমার্থক শব্দ','বিপরীতার্থক শব্দ','এককথায় প্রকাশ','শুদ্ধ বানান','শব্দ ও শব্দের উৎস','ব্যাকরণের নিয়ম'];
  const dict={abandon:{bn:'পরিত্যাগ করা',pron:'əˈbændən',pos:'verb',syn:'leave, desert',ant:'keep, retain',ex:'He decided to abandon the plan.',forms:'abandoned, abandoning',related:'abandonment'},resilient:{bn:'দৃঢ়প্রতিজ্ঞ; দ্রুত ঘুরে দাঁড়াতে সক্ষম',pron:'rɪˈzɪliənt',pos:'adjective',syn:'strong, adaptable',ant:'fragile, weak',ex:'She is resilient in difficult situations.',forms:'resilience, resiliently',related:'resist'},অমর:{en:'immortal',pron:'অ-মর',pos:'বিশেষণ',syn:'চিরস্থায়ী',ant:'মরণশীল',ex:'কীর্তিমান মানুষ অমর হয়ে থাকেন।',forms:'অমরত্ব',related:'চিরন্তন'}};
  function dictLookup(q){const k=q.trim().toLowerCase();if(dict[k])return {...dict[k],word:q};const hit=Object.entries(dict).find(([x,v])=>x.includes(k)||v.bn?.includes(q));return hit?{...hit[1],word:q}:null}
  function addWord(kind,word){P[kind]=[...new Set([...(P[kind]||[]),word])];saveP(P);toast(kind==='savedWords'?'⭐ Saved':'Added to '+(kind==='vocab'?'Vocabulary':'Weak Words'));renderDictionary();}
  window.addPhaseWord=addWord;
  function phaseNav(active){return `<div class="phase-nav"><button class="${active==='dashboard'?'active':''}" onclick="navigate('dashboard')">⌂ Home</button><button class="${active==='gk'?'active':''}" onclick="navigate('daily-gk')">🧠 Daily GK</button><button class="${active==='chat'?'active':''}" onclick="navigate('web-chat')">🌐 Web Chat</button><button class="${active==='dict'?'active':''}" onclick="navigate('dictionary')">📖 Dictionary</button><button class="${active==='memory'?'active':''}" onclick="navigate('memorizing')">🧩 Memorizing</button><button class="${active==='nav'?'active':''}" onclick="navigate('navigator')">🎓 Navigator</button></div>`}
  const oldBottom=bottomNavHtml; bottomNavHtml=function(active){return oldBottom(active)+phaseNav(Router.path.startsWith('daily')?'gk':Router.path.startsWith('web-chat')?'chat':Router.path.startsWith('dictionary')?'dict':Router.path.startsWith('memor')?'memory':Router.path.startsWith('navigator')?'nav':'dashboard')};
  const oldBase=baseTab; baseTab=function(path){if(['daily-gk','web-chat','dictionary','memorizing','navigator'].some(x=>path.startsWith(x)))return 'dashboard';return oldBase(path)};
  const oldRender=render; render=function(){const p=Router.path;if(p==='daily-gk')return renderGK();if(p==='web-chat')return renderWebChat();if(p==='dictionary')return renderDictionary();if(p==='memorizing')return renderMemorizing();if(p==='navigator')return renderNavigator();return oldRender()};
  const oldDash=renderDashboard; renderDashboard=function(){oldDash();setTimeout(()=>{const page=document.querySelector('.page');if(page&&!page.querySelector('.daily-gk-teaser'))page.insertAdjacentHTML('beforeend',`<div class="h2">Daily Recent GK</div><div class="card daily-gk-teaser"><div class="row between"><div><b>আজকের ১০টি ভর্তি-প্রাসঙ্গিক GK</b><div class="muted">প্রতিটি প্রশ্নের উৎসসহ যাচাইকৃত অনুশীলন</div></div>${pBtn('Open','navigate(\'daily-gk\')','btn sm')}</div></div>`)},0)};
  function renderGK(){renderShell(`<div class="explorer-head"><div class="explorer-kicker">Phase 3 · Verified Study Feed</div><div class="explorer-title">Daily Recent GK</div><div class="explorer-subtitle">১০টি ভর্তি-পরীক্ষা উপযোগী প্রশ্ন। প্রতিটি উত্তরের সঙ্গে প্রকাশ্য প্রামাণিক উৎস দেওয়া আছে।</div></div><div class="phase-grid"><div class="phase-metric"><b>${gk.length}</b><span>আজকের প্রশ্ন</span></div><div class="phase-metric"><b>বাংলা</b><span>সম্পূর্ণ ভাষা</span></div></div>${gk.map((x,i)=>`<article class="card gk-card"><div class="row between"><span class="pill blue">GK ${String(i+1).padStart(2,'0')}</span><a class="muted" target="_blank" href="${x[4]}">উৎস ↗</a></div><h3>${pEsc(x[0])}</h3><div class="gk-options">${x[1].map((o,j)=>`<div class="option ${o===x[2]?'correct':''}"><span>${'কখগঘ'[j]}</span>${pEsc(o)}</div>`).join('')}</div><div class="answer-box"><b>উত্তর:</b> ${pEsc(x[2])}</div></article>`).join('')}`,{title:'Daily GK',back:"navigate('dashboard')"})}
  function renderWebChat(){renderShell(`<div class="explorer-head"><div class="explorer-kicker">Phase 3 · Admission Assistant</div><div class="explorer-title">Web AI / Google Information Chat</div><div class="explorer-subtitle">প্রশ্ন করুন। প্রকাশ্য Wikipedia তথ্য ও উৎসের মাধ্যমে সংক্ষিপ্ত উত্তর পাওয়ার চেষ্টা করবে; নেটওয়ার্ক না থাকলে পরিষ্কার fallback দেখাবে।</div></div><div id="chatLog" class="chat-log"><div class="chat-bubble assistant">আমি Admission Assistant। ভর্তি, সাধারণ জ্ঞান বা কোনো বিষয় সম্পর্কে প্রশ্ন করুন।</div></div><form class="card chat-form" onsubmit="askWebChat(event)"><input id="chatInput" class="input" placeholder="বাংলা বা English-এ প্রশ্ন লিখুন…" required><button class="btn">Search</button></form>`,{title:'Admission Assistant',back:"navigate('dashboard')"})}
  window.askWebChat=async function(e){e.preventDefault();const input=document.getElementById('chatInput'),q=input.value.trim();if(!q)return;const log=document.getElementById('chatLog');log.insertAdjacentHTML('beforeend',`<div class="chat-bubble user">${pEsc(q)}</div><div class="chat-bubble assistant" id="chatLoading">তথ্য খোঁজা হচ্ছে…</div>`);input.value='';try{const r=await fetch('https://en.wikipedia.org/api/rest_v1/page/summary/'+encodeURIComponent(q.replace(/\s+/g,'_')));if(!r.ok)throw Error('unavailable');const d=await r.json();document.getElementById('chatLoading').innerHTML=d.extract?`${pEsc(d.extract)}<br><a target="_blank" href="${d.content_urls?.desktop?.page||'#'}">Source ↗</a>`:'এই প্রশ্নের নির্ভরযোগ্য ফল পাওয়া যায়নি।';}catch(err){document.getElementById('chatLoading').textContent='ওয়েব তথ্য এখন পাওয়া যাচ্ছে না। অনুগ্রহ করে পরে আবার চেষ্টা করুন বা Daily GK-এর উৎসগুলো দেখুন।';}}
  function renderDictionary(){const q=Router.params?.q||'';const r=q?dictLookup(q):null;renderShell(`<div class="explorer-head"><div class="explorer-kicker">Phase 4 · Connected Lexicon</div><div class="explorer-title">Ultimate Dictionary</div><div class="explorer-subtitle">English বা বাংলা শব্দ খুঁজুন। Dictionary, Vocabulary এবং Weak Words আলাদা কিন্তু connected।</div></div><form class="card dict-search" onsubmit="searchDict(event)"><input id="dictQ" class="input" value="${pEsc(q)}" placeholder="যেমন: resilient / অমর" required><button class="btn">Search</button></form>${r?`<article class="card dict-card"><div class="row between"><div><span class="pill blue">${pEsc(r.pos)}</span><h2>${pEsc(r.word)}</h2><div class="pron">/${pEsc(r.pron)}/</div></div><button class="iconbtn" onclick="addPhaseWord('savedWords','${pEsc(r.word)}')">⭐</button></div><div class="dict-grid"><div><b>বাংলা অর্থ / English meaning</b><p>${pEsc(r.bn||r.en)}</p></div><div><b>Synonyms / সমার্থক</b><p>${pEsc(r.syn)}</p></div><div><b>Antonyms / বিপরীতার্থক</b><p>${pEsc(r.ant)}</p></div><div><b>Example sentence</b><p>${pEsc(r.ex)}</p></div><div><b>Word forms</b><p>${pEsc(r.forms)}</p></div><div><b>Related words</b><p>${pEsc(r.related)}</p></div></div><div class="row dict-actions">${pBtn('📚 Add to Vocabulary',`addPhaseWord('vocab','${pEsc(r.word)}')`,'btn secondary')}${pBtn('🔴 Add to Weak Words',`addPhaseWord('weak','${pEsc(r.word)}')`,'btn danger')}</div></article>`:(q?`<div class="card empty">এই শব্দটি local lexicon-এ নেই। অনুগ্রহ করে বানান যাচাই করুন অথবা Web Chat-এ শব্দটির অর্থ জিজ্ঞাসা করুন।</div>`:'')}<div class="grid2"><div class="card"><b>⭐ Saved</b><p class="muted">${P.savedWords.length} words</p><div>${P.savedWords.map(pEsc).join(', ')||'—'}</div></div><div class="card"><b>📚 Vocabulary</b><p class="muted">${P.vocab.length} words</p><div>${P.vocab.map(pEsc).join(', ')||'—'}</div></div></div>`,{title:'Dictionary',back:"navigate('dashboard')"})}
  window.searchDict=e=>{e.preventDefault();const q=document.getElementById('dictQ').value.trim();Router.params={q};navigate('dictionary')};
  function renderMemorizing(){const all=[...engCats.map(x=>['English',x]),...benCats.map(x=>['বাংলা',x])];renderShell(`<div class="explorer-head"><div class="explorer-kicker">Phase 4 · Smart Memorizing Center</div><div class="explorer-title">Memorizing Center</div><div class="explorer-subtitle">English ও বাংলা আলাদা card/category, একই spaced-repetition ভিত্তিক progress-এর সঙ্গে সংযুক্ত।</div></div><div class="memory-section"><h2>English Memorizing</h2><div class="category-grid">${engCats.map((x,i)=>memoryCard('English',x,i)).join('')}</div></div><div class="memory-section"><h2>বাংলা Memorizing</h2><div class="category-grid">${benCats.map((x,i)=>memoryCard('বাংলা',x,i)).join('')}</div></div>`,{title:'Smart Memorizing',back:"navigate('dashboard')"})}
  function memoryCard(lang,name,i){return `<article class="card memory-card"><span class="pill ${lang==='English'?'blue':'green'}">${lang}</span><h3>${pEsc(name)}</h3><p class="muted">Recall → MCQ → Matching → Flashcard → Reverse → Timed Test → Weak Items → Final Revision</p><button class="btn sm" onclick="startMemory('${pEsc(lang)}','${pEsc(name)}')">Start category</button></article>`}
  window.startMemory=function(lang,name){const key=lang+' · '+name;P.examHistory.push({key,mode:'Recall',at:Date.now()});saveP(P);openModal(`<h3>${pEsc(name)}</h3><p class="muted">${pEsc(lang)} category study session started. Use the existing Exam Center for question practice, and mark weak items from your revision flows.</p><div class="row"><button class="btn" onclick="closeModal();navigate('exam/setup')">Open Exam Center</button><button class="btn ghost" onclick="closeModal()">Close</button></div>`)};
  function renderNavigator(){const uni=Router.params?.uni||'DU',unit=Router.params?.unit||'A',year=Router.params?.year||'2025-26';renderShell(`<div class="explorer-head"><div class="explorer-kicker">Phase 5 · Current Preparation Map</div><div class="explorer-title">Admission Master Navigator</div><div class="explorer-subtitle">বিশ্ববিদ্যালয়, unit এবং session নির্বাচন করে এক জায়গায় syllabus, pattern, trend ও official sources দেখুন।</div></div><div class="card nav-selector"><select id="navUni" class="input"><option ${uni==='DU'?'selected':''}>DU</option><option ${uni==='JU'?'selected':''}>JU</option></select><select id="navUnit" class="input"><option>A</option><option>B</option><option>C</option><option>D</option></select><select id="navYear" class="input"><option>2025-26</option><option>2024-25</option></select><button class="btn" onclick="updateNavigator()">Update</button></div><div class="navigator-hero card"><span class="pill blue">${uni} · Unit ${unit} · ${year}</span><h2>Preparation Dashboard</h2><p class="muted">Current official notice যাচাই করতে নিচের source links ব্যবহার করুন। Exam date পরিবর্তন হতে পারে—official notice-কে সর্বশেষ reference হিসেবে ধরুন।</p><div class="grid2"><div><b>Current syllabus</b><p>বাংলা, English, সাধারণ জ্ঞান এবং unit-specific subject coverage।</p></div><div><b>Question pattern</b><p>MCQ ভিত্তিক practice; negative marking ও marks distribution notice অনুযায়ী যাচাই করুন।</p></div><div><b>Topic importance</b><p>আপনার existing practice history ও weak items-এর ওপর priority তৈরি করুন।</p></div><div><b>Previous question trend</b><p>Repeated topic চিহ্নিত করতে Question Bank এবং Smart Mistake Book ব্যবহার করুন।</p></div></div></div><div class="grid2"><div class="card"><h3>Topic coverage</h3><p>🟢 Covered topics: ${P.covered.length||0}</p><p>🔴 Uncovered topics: ${Math.max(0,engCats.length+benCats.length-P.covered.length)}</p><p>🟡 Weak topics: ${P.weak.length}</p></div><div class="card"><h3>Exam / deadline information</h3><p class="muted">এই তথ্য session ও unit অনুযায়ী পরিবর্তনশীল। Official notice দেখুন।</p><a class="btn secondary" target="_blank" href="https://admission.eis.du.ac.bd/">DU official admission ↗</a><a class="btn secondary" target="_blank" href="https://ju-admission.org/">JU official admission ↗</a></div></div><div class="card"><h3>Official notices / sources</h3><p><a target="_blank" href="https://admission.eis.du.ac.bd/">ঢাকা বিশ্ববিদ্যালয় Admission Portal</a></p><p><a target="_blank" href="https://ju-admission.org/">জাহাঙ্গীরনগর বিশ্ববিদ্যালয় Admission Portal</a></p><p><a target="_blank" href="https://ugc.gov.bd/">বাংলাদেশ বিশ্ববিদ্যালয় মঞ্জুরি কমিশন</a></p><button class="btn" onclick="navigate('exam/setup')">🎯 Start Preparation</button></div>`,{title:'Admission Navigator',back:"navigate('dashboard')"})}
  window.updateNavigator=()=>{Router.params={uni:document.getElementById('navUni').value,unit:document.getElementById('navUnit').value,year:document.getElementById('navYear').value};renderNavigator()};
  const origRenderShell=renderShell;
  const style=document.createElement('style');style.textContent=`.phase-nav{display:flex;gap:6px;overflow:auto;padding:8px 12px;border-top:1px solid var(--border);background:var(--card);position:sticky;bottom:64px;z-index:4}.phase-nav button{white-space:nowrap;border:1px solid var(--border);background:transparent;border-radius:999px;padding:7px 10px;color:var(--muted);font-size:11px}.phase-nav button.active{background:var(--primary);color:#fff;border-color:var(--primary)}.gk-card h3{line-height:1.45;margin:14px 0}.gk-options{display:grid;grid-template-columns:1fr 1fr;gap:8px}.option{padding:10px;border:1px solid var(--border);border-radius:10px}.option span{font-weight:800;margin-right:8px}.option.correct{border-color:#2f9e72;background:rgba(47,158,114,.1)}.answer-box{margin-top:12px;padding:10px;border-radius:10px;background:rgba(47,158,114,.12)}.chat-log{display:flex;flex-direction:column;gap:10px;margin-bottom:12px}.chat-bubble{max-width:88%;padding:11px 13px;border-radius:14px;line-height:1.5}.chat-bubble.assistant{background:var(--card);border:1px solid var(--border);align-self:flex-start}.chat-bubble.user{background:var(--primary);color:#fff;align-self:flex-end}.chat-form{display:flex;gap:8px}.chat-form .input{flex:1}.dict-grid{display:grid;grid-template-columns:1fr 1fr;gap:14px;margin-top:18px}.dict-grid p{margin:5px 0}.pron{color:var(--muted)}.dict-actions{margin-top:18px;flex-wrap:wrap}.category-grid{display:grid;grid-template-columns:repeat(2,1fr);gap:10px}.memory-section{margin:18px 0}.memory-card h3{font-size:15px}.memory-card .muted{font-size:12px;line-height:1.5}.nav-selector{display:grid;grid-template-columns:1fr 1fr 1fr auto;gap:8px}.navigator-hero{border-left:4px solid var(--primary)}.navigator-hero h2{margin:14px 0 6px}.navigator-hero p{line-height:1.55}.card a{color:var(--primary)}@media(max-width:620px){.gk-options,.dict-grid,.category-grid,.nav-selector{grid-template-columns:1fr}.chat-form{flex-direction:column}.phase-nav{bottom:62px}}`;document.head.appendChild(style);
})();
