import { JSDOM } from 'jsdom';
import { readFileSync } from 'fs';
const code = readFileSync('/home/user/demo/splash-3d.js', 'utf8');
const dom = new JSDOM('<!DOCTYPE html><html><head></head><body><div id="app"><main class="app-loading" id="ahSplash"></main></div></body></html>', { runScripts: 'dangerously', pretendToBeVisual: true });
const w = dom.window;
w.matchMedia = () => ({ matches: false });
const s = w.document.createElement('script');
s.textContent = code;
w.document.body.appendChild(s);
const A = w.AdmissionSplash3D;
let pass = 0, fail = 0;
const t = (n, c) => { if (c) { pass++; console.log('  ✓', n); } else { fail++; console.log('  ✗', n); } };
t('AdmissionSplash3D exists', !!A);
A.mount(w.document.getElementById('ahSplash'));
const scene = w.document.querySelector('.ahfs-scene');
t('scene mounted', !!scene);
t('hero tile present', !!scene.querySelector('.ahfs-tile'));
t('spark svg present', !!scene.querySelector('.ahfs-spark'));
t('6 floating objects', scene.querySelectorAll('.ahfs-obj').length === 6);
t('orbit rings 2', scene.querySelectorAll('.ahfs-ring').length === 2);
t('platform layers', scene.querySelectorAll('.ahfs-platform .p1,.ahfs-platform .p2,.ahfs-platform .p3').length === 3);
t('title "Admission Hub"', scene.querySelector('.ahfs-title').textContent.includes('Admission'));
t('tagline বাংলা', scene.querySelector('.ahfs-tag').textContent.includes('ভর্তি প্রস্তুতির'));
t('stage text বাংলা', scene.querySelector('.ahfs-stage-text').textContent.includes('স্টাডি স্পেস'));
t('NO demo data (DU/unit/Bangla নয়)',
  !/DU|বিশ্ববিদ্যালয়|A Unit|B Unit|Bangla|English|GK/.test(scene.textContent.replace('ঠিকানা','')));
A.setStage('তোমার বিষয় প্রস্তুত হচ্ছে…');
t('setStage updates', scene.querySelector('.ahfs-stage-text').textContent.includes('বিষয়'));
A.setProgress(0.5);
t('setProgress bar scaleX', scene.querySelector('.ahfs-bar').style.transform.includes('0.5'));
const p = A.dismiss(300);
p.then(() => {
  t('dismiss removed overlay', !w.document.querySelector('.ahfs-overlay'));
  const played = scene.classList.contains('ahfs-play') || scene.classList.contains('ahfs-still');
  t('animations stopped (still)', scene.classList.contains('ahfs-still'));
  t('scene fully removed from DOM (cleanup)', !w.document.contains(scene));
  console.log(fail === 0 ? '✅ SPLASH TEST PASS (' + pass + ')' : '❌ FAIL ' + fail + ' / pass ' + pass);
  process.exit(fail ? 1 : 0);
});
// safe timeout
setTimeout(() => { console.log('⏰ timeout — dismiss hang'); process.exit(1); }, 4000);
