export const EMAIL_GATEWAY_VERSION = 'phase2b-2';

export const EMAIL_TYPES = Object.freeze({
  EMAIL_VERIFICATION: 'EMAIL_VERIFICATION',
  SIGNUP_VERIFICATION: 'SIGNUP_VERIFICATION',
  PASSWORD_RESET: 'PASSWORD_RESET',
  NEW_DEVICE_VERIFICATION: 'NEW_DEVICE_VERIFICATION',
  LOGIN_SECURITY_CHALLENGE: 'LOGIN_SECURITY_CHALLENGE',
  MFA_CODE: 'MFA_CODE',
  ACCOUNT_RECOVERY: 'ACCOUNT_RECOVERY',
  WELCOME_EMAIL: 'WELCOME_EMAIL',
  SECURITY_ALERT: 'SECURITY_ALERT'
});

export const EMAIL_PRIORITIES = Object.freeze({
  CRITICAL: 'CRITICAL',
  HIGH: 'HIGH',
  NORMAL: 'NORMAL',
  LOW: 'LOW'
});

export const ROUTER_MODES = Object.freeze({
  PRIORITY: 'priority',
  WEIGHTED: 'weighted',
  FAILOVER: 'failover',
  QUOTA: 'quota',
  HYBRID: 'hybrid'
});

export const PROVIDER_IDS = Object.freeze([
  'resend', 'brevo', 'mailjet', 'mailtrap',
  'mailersend', 'sendpulse', 'emailoctopus', 'courier'
]);

export const LEGACY_PROVIDER_IDS = Object.freeze([
  'zeptomail', 'ses', 'mailgun', 'sendgrid', 'smtp2go',
  'elasticemail', 'postmark', 'google-apps-script'
]);

export const DELIVERY_EVENT_PROVIDER_IDS = Object.freeze([...new Set([...PROVIDER_IDS, ...LEGACY_PROVIDER_IDS])]);

export const PROVIDER_CAPABILITIES = Object.freeze({
  API: 'api',
  SMTP: 'smtp',
  TRANSACTIONAL: 'transactional',
  HTML: 'html',
  TEXT: 'text',
  CUSTOM_DOMAIN: 'custom-domain',
  WEBHOOKS: 'webhooks',
  DELIVERY_EVENTS: 'delivery-events',
  IDEMPOTENCY: 'idempotency'
});

export const EMAIL_FAILURE_CODES = Object.freeze({
  TIMEOUT: 'TIMEOUT',
  NETWORK_ERROR: 'NETWORK_ERROR',
  DNS_ERROR: 'DNS_ERROR',
  FIVE_XX_SERVER_ERROR: '5XX_SERVER_ERROR',
  RATE_LIMIT: 'RATE_LIMIT',
  QUOTA_EXCEEDED: 'QUOTA_EXCEEDED',
  AUTHENTICATION_ERROR: 'AUTHENTICATION_ERROR',
  INVALID_REQUEST: 'INVALID_REQUEST',
  DOMAIN_ERROR: 'DOMAIN_ERROR',
  RECIPIENT_REJECTED: 'RECIPIENT_REJECTED',
  PROVIDER_SUSPENDED: 'PROVIDER_SUSPENDED',
  NOT_CONFIGURED: 'NOT_CONFIGURED',
  NO_ELIGIBLE_PROVIDER: 'NO_ELIGIBLE_PROVIDER',
  IDEMPOTENCY_CONFLICT: 'IDEMPOTENCY_CONFLICT',
  DELIVERY_UNCERTAIN: 'DELIVERY_UNCERTAIN',
  RATE_LIMITED: 'RATE_LIMITED',
  UNAUTHORIZED: 'UNAUTHORIZED',
  REPLAY_DETECTED: 'REPLAY_DETECTED',
  STORAGE_UNAVAILABLE: 'STORAGE_UNAVAILABLE',
  STRONG_STORE_REQUIRED: 'STRONG_STORE_REQUIRED',
  INVALID_CONFIGURATION: 'INVALID_CONFIGURATION',
  UNKNOWN: 'UNKNOWN'
});

export const CIRCUIT_STATES = Object.freeze({
  CLOSED: 'CLOSED',
  OPEN: 'OPEN',
  HALF_OPEN: 'HALF_OPEN'
});

export const QUOTA_STATES = Object.freeze({
  NORMAL: 'NORMAL',
  LOW: 'LOW',
  CRITICAL: 'CRITICAL',
  EXHAUSTED: 'EXHAUSTED',
  UNKNOWN: 'UNKNOWN'
});

export const PROVIDER_HEALTH = Object.freeze({
  HEALTHY: 'HEALTHY',
  DEGRADED: 'DEGRADED',
  RATE_LIMITED: 'RATE_LIMITED',
  QUOTA_LOW: 'QUOTA_LOW',
  QUOTA_EXHAUSTED: 'QUOTA_EXHAUSTED',
  UNHEALTHY: 'UNHEALTHY',
  OFFLINE: 'OFFLINE',
  DISABLED: 'DISABLED'
});

export const DELIVERY_STATES = Object.freeze({
  PENDING: 'PENDING',
  ATTEMPTING: 'ATTEMPTING',
  ACCEPTED: 'ACCEPTED',
  QUEUED: 'QUEUED',
  SENT: 'SENT',
  DELIVERED: 'DELIVERED',
  BOUNCED: 'BOUNCED',
  REJECTED: 'REJECTED',
  COMPLAINED: 'COMPLAINED',
  FAILED: 'FAILED',
  UNCERTAIN: 'UNCERTAIN',
  RATE_LIMITED: 'RATE_LIMITED'
});

export const FINAL_REQUEST_STATES = Object.freeze(new Set([
  DELIVERY_STATES.ACCEPTED,
  DELIVERY_STATES.QUEUED,
  DELIVERY_STATES.SENT,
  DELIVERY_STATES.DELIVERED,
  DELIVERY_STATES.BOUNCED,
  DELIVERY_STATES.REJECTED,
  DELIVERY_STATES.COMPLAINED,
  DELIVERY_STATES.FAILED,
  DELIVERY_STATES.UNCERTAIN,
  DELIVERY_STATES.RATE_LIMITED
]));

export const RETRYABLE_PROVIDER_FAILURES = Object.freeze(new Set([
  EMAIL_FAILURE_CODES.TIMEOUT,
  EMAIL_FAILURE_CODES.NETWORK_ERROR,
  EMAIL_FAILURE_CODES.DNS_ERROR,
  EMAIL_FAILURE_CODES.FIVE_XX_SERVER_ERROR,
  EMAIL_FAILURE_CODES.RATE_LIMIT,
  EMAIL_FAILURE_CODES.QUOTA_EXCEEDED
]));

export const FAILOVER_ELIGIBLE_FAILURES = Object.freeze(new Set([
  EMAIL_FAILURE_CODES.NETWORK_ERROR,
  EMAIL_FAILURE_CODES.DNS_ERROR,
  EMAIL_FAILURE_CODES.FIVE_XX_SERVER_ERROR,
  EMAIL_FAILURE_CODES.RATE_LIMIT,
  EMAIL_FAILURE_CODES.QUOTA_EXCEEDED,
  EMAIL_FAILURE_CODES.AUTHENTICATION_ERROR,
  EMAIL_FAILURE_CODES.DOMAIN_ERROR,
  EMAIL_FAILURE_CODES.PROVIDER_SUSPENDED
]));

export const INTERNAL_EMAIL_PATHS = Object.freeze({
  SEND: '/internal/email/send',
  HEALTH: '/internal/email/health',
  DELIVERY_EVENT: '/internal/email/delivery-event'
});
