export const AUTH_FOUNDATION_VERSION = 'phase2a-1';

export const AUTH_STATES = Object.freeze({
  INITIALIZING: 'INITIALIZING',
  CHECKING_SESSION: 'CHECKING_SESSION',
  UNAUTHENTICATED: 'UNAUTHENTICATED',
  AUTHENTICATING: 'AUTHENTICATING',
  AUTHENTICATED: 'AUTHENTICATED',
  REFRESHING: 'REFRESHING',
  RECOVERING: 'RECOVERING',
  LOGGING_OUT: 'LOGGING_OUT'
});

export const AUTH_METHODS = Object.freeze({
  PASSWORD: 'password',
  EMAIL_OTP: 'email-otp',
  GOOGLE: 'google',
  PASSKEY: 'passkey'
});

export const AUTH_ERROR_TYPES = Object.freeze({
  USER_ERROR: 'USER_ERROR',
  NETWORK_ERROR: 'NETWORK_ERROR',
  AUTH_ERROR: 'AUTH_ERROR',
  SESSION_ERROR: 'SESSION_ERROR',
  SERVER_ERROR: 'SERVER_ERROR',
  SECURITY_ERROR: 'SECURITY_ERROR',
  UNKNOWN_ERROR: 'UNKNOWN_ERROR'
});

export const AUTH_ERROR_CODES = Object.freeze({
  INVALID_INPUT: 'INVALID_INPUT',
  INVALID_STATE: 'INVALID_STATE',
  INVALID_RESPONSE: 'INVALID_RESPONSE',
  NOT_CONFIGURED: 'NOT_CONFIGURED',
  UNSUPPORTED: 'UNSUPPORTED',
  BUSY: 'BUSY',
  CANCELLED: 'CANCELLED',
  TIMEOUT: 'TIMEOUT',
  NETWORK_FAILURE: 'NETWORK_FAILURE',
  AUTHENTICATION_FAILED: 'AUTHENTICATION_FAILED',
  SESSION_INVALID: 'SESSION_INVALID',
  SESSION_EXPIRED: 'SESSION_EXPIRED',
  SECURITY_CHALLENGE_REQUIRED: 'SECURITY_CHALLENGE_REQUIRED',
  RATE_LIMITED: 'RATE_LIMITED',
  SERVER_FAILURE: 'SERVER_FAILURE',
  STALE_OPERATION: 'STALE_OPERATION',
  UNKNOWN: 'UNKNOWN'
});

export const AUTH_PUBLIC_METHODS = Object.freeze([
  'initialize',
  'getCurrentUser',
  'getSession',
  'getState',
  'isAuthenticated',
  'subscribe',
  'signIn',
  'signOut',
  'signUp',
  'verify',
  'recover'
]);

export const AUTH_EVENT_TYPES = Object.freeze({
  STATE_CHANGED: 'STATE_CHANGED',
  OPERATION_STARTED: 'OPERATION_STARTED',
  OPERATION_FINISHED: 'OPERATION_FINISHED',
  OPERATION_FAILED: 'OPERATION_FAILED'
});
